{
  accelFactor = "0.0350939";
  enable = true;
  twoFingerScroll = true;
  vertEdgeScroll = false;
  horizTwoFingerScroll = false;
  horizEdgeScroll = true;
  minSpeed = "0.6";
  maxSpeed = "1.75";
  palmDetect = true;
  # disable paste with 2 fingers:
  additionalOptions = ''
    Option "TapButton2" "3"
  '';
  #     Driver "synaptics"
  #     MatchIsTouchpad "on"
  # 	Option "LeftEdge" "1781"
  # 	Option "RightEdge" "5579"
  # 	Option "TopEdge" "1660"
  # 	Option "BottomEdge" "4760"
  # 	Option "FingerLow" "25"
  # 	Option "FingerHigh" "30"
  # 	Option "FingerPress" "256"
  # 	Option "MaxTapTime" "259"
  # 	Option "MaxTapMove" "265"
  # 	Option "MaxDoubleTapTime" "180"
  # 	Option "SingleTapTimeout" "180"
  # 	Option "ClickTime" "100"
  # 	Option "FastTaps" "1"
  # 	Option "EmulateMidButtonTime" "75"
  # 	Option "EmulateTwoFingerMinZ" "282"
  # 	Option "EmulateTwoFingerMinW" "7"
  # 	Option "VertScrollDelta" "111"
  # 	Option "HorizScrollDelta" "111"
  # 	Option "VertEdgeScroll" "0"
  # 	Option "HorizEdgeScroll" "1"
  # 	Option "CornerCoasting" "0"
  # 	Option "VertTwoFingerScroll" "1"
  # 	Option "HorizTwoFingerScroll" "0"
  # 	Option "AccelFactor" "0.0350939"
  # 	Option "TrackstickSpeed" "40"
  # 	Option "EdgeMotionMinZ" "30"
  # 	Option "EdgeMotionMaxZ" "160"
  # 	Option "EdgeMotionMinSpeed" "1"
  # 	Option "EdgeMotionMaxSpeed" "455"
  # 	Option "EdgeMotionUseAlways" "0"
  # 	Option "TouchpadOff" "0"
  # 	Option "LockedDrags" "0"
  # 	Option "LockedDragTimeout" "5000"
  # 	Option "RTCornerButton" "0"
  # 	Option "RBCornerButton" "0"
  # 	Option "LTCornerButton" "0"
  # 	Option "LBCornerButton" "0"
  # 	Option "TapButton1" "1"
  # 	Option "TapButton2" "3"
  # 	Option "TapButton3" "2"
  # 	Option "ClickFinger1" "1"
  # 	Option "ClickFinger2" "1"
  # 	Option "ClickFinger3" "1"
  # 	Option "CircularScrolling" "0"
  # 	Option "CircScrollDelta" "0.1"
  # 	Option "CircScrollTrigger" "0"
  # 	Option "CircularPad" "0"
  # 	Option "PalmMinWidth" "10"
  # 	Option "PalmMinZ" "200"
  # 	Option "CoastingSpeed" "20"
  # 	Option "CoastingFriction" "50"
  # 	Option "PressureMotionMinZ" "30"
  # 	Option "PressureMotionMaxZ" "160"
  # 	Option "PressureMotionMinFactor" "1"
  # 	Option "PressureMotionMaxFactor" "1"
  # 	Option "GrabEventDevice" "1"
  # 	Option "TapAndDragGesture" "1"
  # 	Option "AreaLeftEdge" "0"
  # 	Option "AreaRightEdge" "0"
  # 	Option "AreaTopEdge" "0"
  # 	Option "AreaBottomEdge" "0"
  # 	Option "HorizHysteresis" "28"
  # 	Option "VertHysteresis" "28"
  # 	Option "ClickPad" "0"
  # '';
}
